### ISSUE TITLE
Mechanical Design – missing details

### ISSUE THREAD

**Issue by TatianaResend** [TatianaResend/SPIF-A_v2#14]
- [x] The reducer can also be fixed in the connection area between the reducer and the motor. #12 
- [x] Confirm that the ```27620-1020``` component supports the stress. #5 
- [x] Simulate the structure. #5
- [x] X-axis: decide whether one or two motors. #13 
- [x] Fixing the table and the linear actuator. #13

**Comment by TatianaResend** [comment]
I've done the missing details
